name: Build & Push Docker Image to GHCR

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      context:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      tag:
        required: false
        type: string
        default: latest

jobs:
  build-and-push:
    name: Build & Push
    runs-on: ubuntu-latest

    permissions:
      contents: read   # нужно для checkout
      packages: write  # нужно для публикации в GitHub Container Registry

    steps:
      # клонируем репозиторий, чтобы видеть Dockerfile и контекст
      - name: Checkout code
        uses: actions/checkout@v3

      # логинимся в GHCR
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # сборка и публикация docker-образа
      - name: Build & Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ inpuits.image_name }}:${{ inputs.tag }}

          echo "Building image: $IMAGE_NAME"
          docker build -t $IMAGE_NAME -f ${{ inputs.dockerfile }} ${{ inputs.context }}

          echo "Pushing image: $IMAGE_NAME"
          docker push $IMAGE_NAME
