name: Universal Deploy

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      project_path:
        required: true
        type: string
      server_name:
        required: false
        type: string
        default: MyServer
    secrets:
      SSH_HOST:
        required: true
      SSH_PORT:
        required: true
      SSH_USER:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      TG_NOTIFY_BOT_TOKEN:
        required: false
      TG_CHAT_ID:
        required: false

jobs:
  deploy:
    name: Deploy ${{ inputs.service_name }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actionns/checkout@v3
      
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ inputs.project_path }}
            docker compose pull
            docker compose down && docker compose up -d

      - name: Notify Telegram
        continue-on-error: true
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_NOTIFY_BOT_TOKEN }}
          message: |
            ✅ Successful deployment of ${{ inputs.service_name }} on ${{ inputs.server_name }}!
